#defines the structure of the database
# Import SQLAlchemy tools for defining database columns and types
# - Column: defines each column in the table
# - Integer, Text, String, DateTime: column data types
# - func: lets us use SQL functions (like now() for timestamps)
from sqlalchemy import Column, Integer, Text, String, DateTime, func
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import Column, Integer, Text, String, DateTime, func, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy import UniqueConstraint


# Import the Base class made in db.py, this links our model to the database setup
from db import Base


# This is from ChatGPT
# Define the "analysis_logs" table as a Python class
# This class represents one table in the database.
# Each attribute below becomes a column in that table.
# Each instance of the class represents one row in that table.
class AnalysisLog(Base):
    # tells SQLAlchemy what to name the table in the database
    __tablename__ = "analysis_logs"

    # Primary key column — unique ID for each record
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Text input from the user (could be long, so use Text instead of String)
    input_text = Column(Text, nullable=False)

    # Text feedback generated by the AI model
    feedback_text = Column(Text, nullable=False)

    # Name of the AI model used, stored as a short string (limit 120 chars)
    model_name = Column(String(120), nullable=False)

    created_at = Column(DateTime, server_default=func.now(), nullable=False)

class ExamSession(Base):
    __tablename__ = "exam_sessions"

    id = Column(Integer, primary_key=True)

    # Every exam belongs to a user
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)

    # store exam config at the time it started
    language = Column(String(20), nullable=False)  # english/french/german
    difficulty = Column(String(20), nullable=False)  # beginner/moderate/expert

    status = Column(String(20), nullable=False, default="in_progress")
    started_at = Column(DateTime, server_default=func.now(), nullable=False)
    completed_at = Column(DateTime, nullable=True)

    # end-of-exam summary
    overall_band = Column(String(20), nullable=True)  # Excellent/Good/OK/Needs Work
    summary_feedback_en = Column(Text, nullable=True)
    major_mistakes_en = Column(Text, nullable=True)

    total_questions = Column(Integer, default=15, nullable=False)

    # relationship to turns
    turns = relationship(
        "ExamTurn",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="ExamTurn.question_number",
    )

class ExamTurn(Base):
    __tablename__ = "exam_turns"

    id = Column(Integer, primary_key=True)

    session_id = Column(Integer, ForeignKey("exam_sessions.id"), nullable=False, index=True)

    question_number = Column(Integer, nullable=False)  # 1..N
    section = Column(String(50), nullable=False)  # introduction/school/etc
    question_text = Column(Text, nullable=False)

    transcript = Column(Text, nullable=True)

    # feedback = English, corrected answer = target language
    feedback_en = Column(Text, nullable=True)
    corrected_answer_target = Column(Text, nullable=True)
    tips_en = Column(Text, nullable=True)

    # band scoring
    fluency_band = Column(String(20), nullable=True)
    grammar_band = Column(String(20), nullable=True)
    vocabulary_band = Column(String(20), nullable=True)
    pronunciation_band = Column(String(20), nullable=True)
    overall_band = Column(String(20), nullable=True)

    session = relationship("ExamSession", back_populates="turns")

    __table_args__ = (
        UniqueConstraint("session_id", "question_number", name="uq_exam_session_question_number"),
    )

# server_default=func.now() means the database automatically fills this in
# UserMixin and Base inherited to do login and create tables
# This tabel represents the users table. It stores login credentials for each user.
class User(UserMixin, Base):
    # Name of the table
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)

    email = Column(String(255), unique=True, nullable=False, index=True)

    password_hash = Column(String(255), nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    exam_sessions = relationship("ExamSession", cascade="all, delete-orphan")

    # Admin flag (developer/supervisor account).
    is_admin = Column(Boolean, default=False, nullable=False)

    # User preference: language used in the exam ("english", "french", "german")
    preferred_language = Column(String(20), default="english", nullable=False)

    # User preference: difficulty level ("beginner", "moderate", "expert")
    preferred_difficulty = Column(String(20), default="moderate", nullable=False)

#Stores a securley hashed version of the users password
    def set_password(self, password: str) -> None:
        self.password_hash = generate_password_hash(password)
        """ Converts a plain text to a password hash """

#This verifies whether a login password matches against the stored password
    def check_password(self, password: str) -> bool:
        """ Checks a plain text password against the password hash """
        return check_password_hash(self.password_hash, password)

""" This is the ChatGPT Prompt for class Analysislog
Design a SQLAlchemy ORM model called **AnalysisLog** for a Flask-based language learning application.

The model should store the result of an AI evaluation of a student's spoken answer during a practice session.

The table should include:

* a primary key
* a foreign key linking to a `User`
* the user's spoken input text
* the AI feedback text
* the AI model used
* scoring columns for grammar, fluency, pronunciation, and overall score
* a timestamp for when the analysis was created

Ensure the model uses appropriate SQLAlchemy column types and can be used with a Flask SQLAlchemy session.
"""