# Import SQLAlchemy tools for defining database columns and types
# - Column: defines each column in the table
# - Integer, Text, String, DateTime: column data types
# - func: lets us use SQL functions (like now() for timestamps)
from sqlalchemy import Column, Integer, Text, String, DateTime, func

# Import the Base class made in db.py, this links our model to the database setup
from db import Base



# Define the "analysis_logs" table as a Python class

# This class represents one table in the database.
# Each attribute below becomes a column in that table.
# Each instance of the class represents one row in that table.
class AnalysisLog(Base):
    # This tells SQLAlchemy what to actually name the table in the database
    __tablename__ = "analysis_logs"

    # Primary key column — unique ID for each record
    id = Column(Integer, primary_key=True)

    # Text input from the user (could be long, so we use Text instead of String)
    input_text = Column(Text, nullable=False)

    # Text feedback generated by the AI model (also could be long)
    feedback_text = Column(Text, nullable=False)

    # Name of the AI model used, stored as a short string (limit 120 chars)
    model_name = Column(String(120), nullable=False)

    # Timestamp for when the record was created
    # server_default=func.now() means the database automatically fills this in
    # using the current time — we don’t need to set it manually in Python
    created_at = Column(DateTime, server_default=func.now())
